// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: user/v1/user.service.proto

package userv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_user_v1_user_service_proto protoreflect.FileDescriptor

const file_user_v1_user_service_proto_rawDesc = "" +
	"\n" +
	"\x1auser/v1/user.service.proto\x12\auser.v1\x1a\x1auser/v1/user.payload.proto\x1a\x1bgoogle/protobuf/empty.proto2\xaf\x02\n" +
	"\vUserService\x12<\n" +
	"\bRegister\x12\x14.user.v1.AuthRequest\x1a\x1a.user.v1.UserTokenResponse\x129\n" +
	"\x05Login\x12\x14.user.v1.AuthRequest\x1a\x1a.user.v1.UserTokenResponse\x12/\n" +
	"\x02Me\x12\x16.google.protobuf.Empty\x1a\x11.user.v1.UserData\x12B\n" +
	"\tListUsers\x12\x19.user.v1.ListUsersRequest\x1a\x1a.user.v1.ListUsersResponse\x122\n" +
	"\x06TesRPC\x12\x16.google.protobuf.Empty\x1a\x10.user.v1.TestRPCB8Z6github.com/siti-nabila/api-contracts/pb/user/v1;userv1b\x06proto3"

var file_user_v1_user_service_proto_goTypes = []any{
	(*AuthRequest)(nil),       // 0: user.v1.AuthRequest
	(*emptypb.Empty)(nil),     // 1: google.protobuf.Empty
	(*ListUsersRequest)(nil),  // 2: user.v1.ListUsersRequest
	(*UserTokenResponse)(nil), // 3: user.v1.UserTokenResponse
	(*UserData)(nil),          // 4: user.v1.UserData
	(*ListUsersResponse)(nil), // 5: user.v1.ListUsersResponse
	(*TestRPC)(nil),           // 6: user.v1.TestRPC
}
var file_user_v1_user_service_proto_depIdxs = []int32{
	0, // 0: user.v1.UserService.Register:input_type -> user.v1.AuthRequest
	0, // 1: user.v1.UserService.Login:input_type -> user.v1.AuthRequest
	1, // 2: user.v1.UserService.Me:input_type -> google.protobuf.Empty
	2, // 3: user.v1.UserService.ListUsers:input_type -> user.v1.ListUsersRequest
	1, // 4: user.v1.UserService.TesRPC:input_type -> google.protobuf.Empty
	3, // 5: user.v1.UserService.Register:output_type -> user.v1.UserTokenResponse
	3, // 6: user.v1.UserService.Login:output_type -> user.v1.UserTokenResponse
	4, // 7: user.v1.UserService.Me:output_type -> user.v1.UserData
	5, // 8: user.v1.UserService.ListUsers:output_type -> user.v1.ListUsersResponse
	6, // 9: user.v1.UserService.TesRPC:output_type -> user.v1.TestRPC
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_user_v1_user_service_proto_init() }
func file_user_v1_user_service_proto_init() {
	if File_user_v1_user_service_proto != nil {
		return
	}
	file_user_v1_user_payload_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_v1_user_service_proto_rawDesc), len(file_user_v1_user_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_v1_user_service_proto_goTypes,
		DependencyIndexes: file_user_v1_user_service_proto_depIdxs,
	}.Build()
	File_user_v1_user_service_proto = out.File
	file_user_v1_user_service_proto_goTypes = nil
	file_user_v1_user_service_proto_depIdxs = nil
}
