// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: profile/v1/profile.service.proto

package profilev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_profile_v1_profile_service_proto protoreflect.FileDescriptor

const file_profile_v1_profile_service_proto_rawDesc = "" +
	"\n" +
	" profile/v1/profile.service.proto\x12\n" +
	"profile.v1\x1a profile/v1/profile.payload.proto2Z\n" +
	"\x0eProfileService\x12H\n" +
	"\rUpdateProfile\x12\x1a.profile.v1.ProfileRequest\x1a\x1b.profile.v1.ProfileResponseB>Z<github.com/siti-nabila/api-contracts/pb/profile/v1;profilev1b\x06proto3"

var file_profile_v1_profile_service_proto_goTypes = []any{
	(*ProfileRequest)(nil),  // 0: profile.v1.ProfileRequest
	(*ProfileResponse)(nil), // 1: profile.v1.ProfileResponse
}
var file_profile_v1_profile_service_proto_depIdxs = []int32{
	0, // 0: profile.v1.ProfileService.UpdateProfile:input_type -> profile.v1.ProfileRequest
	1, // 1: profile.v1.ProfileService.UpdateProfile:output_type -> profile.v1.ProfileResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_profile_v1_profile_service_proto_init() }
func file_profile_v1_profile_service_proto_init() {
	if File_profile_v1_profile_service_proto != nil {
		return
	}
	file_profile_v1_profile_payload_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_profile_v1_profile_service_proto_rawDesc), len(file_profile_v1_profile_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_profile_v1_profile_service_proto_goTypes,
		DependencyIndexes: file_profile_v1_profile_service_proto_depIdxs,
	}.Build()
	File_profile_v1_profile_service_proto = out.File
	file_profile_v1_profile_service_proto_goTypes = nil
	file_profile_v1_profile_service_proto_depIdxs = nil
}
